[package]
name = "market-data"
version = "0.1.0"
edition = "2021"

[dependencies]
databento = "0.20.0"
tokio = { version = "1.43.0", features = ["full"] }
time = "0.3.37"
serde = "1.0.217"
toml = "0.8.20"
log = "0.4.25"
simplelog = "0.12"

